using Dapper;
using Npgsql;
using Rgt.Space.Core.Abstractions.Identity;
using Rgt.Space.Core.Abstractions.Tenancy;
using Rgt.Space.Core.Domain.Entities.Identity;

namespace Rgt.Space.Infrastructure.Persistence.Identity;

public sealed class UserWriteDac : IUserWriteDac
{
    private readonly ITenantConnectionFactory _connFactory;

    public UserWriteDac(ITenantConnectionFactory connFactory)
    {
        _connFactory = connFactory;
    }

    public async Task<Guid> CreateAsync(User user, CancellationToken ct = default)
    {
        var connString = await _connFactory.GetSqlConnectionStringAsync(string.Empty, ct);
        await using var conn = new NpgsqlConnection(connString);

        // Note: ID is generated by DB default (uuid_generate_v7()) if we pass NULL, 
        // but User entity might already have a Guid if created via factory.
        // We'll use the Entity's ID if present, or let DB generate if empty.
        // Actually, User.CreateFromSso uses Guid.NewGuid().
        // So we insert it.

        const string sql = @"
            INSERT INTO users (
                id, display_name, email, contact_number, is_active,
                local_login_enabled, password_hash, password_salt,
                sso_login_enabled, sso_provider, external_id, sso_email,
                created_at, created_by, updated_at, updated_by
            ) VALUES (
                @Id, @DisplayName, @Email, @ContactNumber, @IsActive,
                @LocalLoginEnabled, @PasswordHash, @PasswordSalt,
                @SsoLoginEnabled, @SsoProvider, @ExternalId, @SsoEmail,
                @CreatedAt, @CreatedBy, @UpdatedAt, @UpdatedBy
            ) RETURNING id;";

        // Map Entity properties to params
        var p = new
        {
            user.Id,
            user.DisplayName,
            user.Email,
            user.ContactNumber,
            user.IsActive,
            user.LocalLoginEnabled,
            user.PasswordHash,
            user.PasswordSalt,
            user.SsoLoginEnabled,
            user.SsoProvider,
            user.ExternalId,
            user.SsoEmail,
            user.CreatedAt,
            user.CreatedBy,
            user.UpdatedAt,
            user.UpdatedBy
        };

        return await conn.ExecuteScalarAsync<Guid>(sql, p);
    }

    public async Task UpdateAsync(User user, CancellationToken ct = default)
    {
        var connString = await _connFactory.GetSqlConnectionStringAsync(string.Empty, ct);
        await using var conn = new NpgsqlConnection(connString);

        const string sql = @"
            UPDATE users SET
                display_name = @DisplayName,
                email = @Email,
                contact_number = @ContactNumber,
                is_active = @IsActive,
                updated_at = @UpdatedAt,
                updated_by = @UpdatedBy
            WHERE id = @Id;";

        await conn.ExecuteAsync(sql, new
        {
            user.Id,
            user.DisplayName,
            user.Email,
            user.ContactNumber,
            user.IsActive,
            user.UpdatedAt,
            user.UpdatedBy
        });
    }

    public async Task UpdateLastLoginAsync(Guid userId, string provider, CancellationToken ct = default)
    {
        var connString = await _connFactory.GetSqlConnectionStringAsync(string.Empty, ct);
        await using var conn = new NpgsqlConnection(connString);

        const string sql = @"
            UPDATE users SET
                last_login_at = @Now,
                last_login_provider = @Provider
            WHERE id = @Id;";

        await conn.ExecuteAsync(sql, new
        {
            Id = userId,
            Provider = provider,
            Now = DateTime.UtcNow
        });
    }
}
